# Generated by Django 4.0.2 on 2022-02-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0004_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
