# Generated by Django 4.0.2 on 2022-02-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0005_user_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='static/default_avatar/cool-monkey.jpg', null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
